services:
  mysql:
    image: mysql:8.0
    container_name: football-stats-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: football_stats
    ports:
      - "3307:3306"
    volumes:
      # Persistent data volume
      - mysql_data:/var/lib/mysql
      # Backup file mounted into init folder
      - ./fs-app.sql:/docker-entrypoint-initdb.d/backup.sql:ro
    networks:
      - football-stats-network

  app:
    image: vladbogdadocker/football-stats
    container_name: football-stats-app
    depends_on:
      - mysql
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/football_stats?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - football-stats-network

volumes:
  mysql_data:

networks:
  football-stats-network:
    driver: bridge